# Generated by Django 5.2.5 on 2025-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_invoice_number_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_applied',
            field=models.BooleanField(default=False),
        ),
    ]
