# Generated by Django 5.2.5 on 2025-08-31 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoiceitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['shop_owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(default=1, limit_choices_to={'role__in': ['shop_owner', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='shop_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('name', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_number', 'shop')},
        ),
    ]
