services:
  - type: web
    name: stoqman-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend-domain.vercel.app"
      - key: PYTHON_VERSION
        value: "3.11.0"
    autoDeploy: true
    healthCheckPath: "/api/health/"
